SELECT db_table FROM qnia.qnia_key GROUP BY db_table;
SELECT count(*) AS shape FROM qnia.qnia_key;
SELECT count(*) AS shape FROM mei.mei_key;
SELECT count(*) AS shape FROM gerfin.gerfin_key;
SELECT count(*) AS shape FROM gerfin.db_d_0001;
SELECT count(*) AS shape FROM forex.forex_key;
SELECT count(*) AS shape FROM us.us_key;
SELECT count(*) AS shape FROM intline.intline_key;
SELECT count(*) AS shape FROM asia.asia_key;
SELECT * FROM qnia.qnia_key;
SELECT * FROM mei.mei_key;
SELECT * FROM gerfin.gerfin_key;
SELECT * FROM forex.forex_key;
SELECT * FROM us.us_key;
SELECT * FROM intline.intline_key;
SELECT * FROM asia.asia_key;
DESC qnia.qnia_key;